"use client"

import { useState } from "react"

interface ShareCardDownloadProps {
  shareToken: string
  year: number
}

/**
 * Downloads the 1080x1920 story-format share card generated by the
 * OG image route (?format=card) as a PNG.
 */
export function ShareCardDownload({ shareToken, year }: ShareCardDownloadProps) {
  const [isDownloading, setIsDownloading] = useState(false)
  const [error, setError] = useState(false)

  const handleDownload = async () => {
    setIsDownloading(true)
    setError(false)
    try {
      const response = await fetch(`/api/wrapped/og-image?token=${shareToken}&format=card`)
      if (!response.ok) throw new Error(`Card generation failed: ${response.status}`)
      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const link = document.createElement("a")
      link.href = url
      link.download = `plex-wrapped-${year}.png`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Failed to download share card:", err)
      setError(true)
    } finally {
      setIsDownloading(false)
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={isDownloading}
      data-testid="wrapped-download-card"
      className="px-4 sm:px-6 py-3 rounded-xl text-sm font-semibold flex items-center gap-2 border border-gold/40 text-gold-bright hover:border-gold hover:bg-gold/10 transition-colors disabled:opacity-50"
      aria-label="Download share card image"
    >
      <svg
        className="w-4 h-4"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        aria-hidden="true"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M12 4v12m0 0l-4-4m4 4l4-4"
        />
      </svg>
      <span>{isDownloading ? "Preparing…" : error ? "Try again" : "Download card"}</span>
    </button>
  )
}
